#! /usr/bin/env bash

#Install Apple CLI Dev tools, java and my preferred homebrew and cask software

xcode-select --install # Works on Mavericks and hopfully above

echo
read -p "Please wait until CLI tools are installed and press enter"  < /dev/tty

ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"

#Synlink into the normal place. Add this to login scripts as well
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

brew tap caskroom/cask
brew tap caskroom/versions

brew install brew-cask
brew install python
brew install node

brew cask install java7
brew cask install atom
brew cask install dropbox
brew cask install google-chrome
brew cask install iterm2
brew cask install minecraft
brew cask install skype
brew cask install smcfancontrol
brew cask install steam
brew cask install intellij-idea-ultimate-eap
brew cask install spotify
brew cask install postgres
brew cask install dash
brew cask install sourcetree
brew cask install spectacle

brew cleanup
brew cask cleanup

curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

